name: collecteverything
services:
  database:
    container_name: Postgre
    image: postgres:16.2-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-volume:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    
  redis:
    container_name: Redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis-volume:/data
  
  migrator:
    container_name: Migrator
    image: ghcr.io/mns-collect-verything/dbmigrator:master
    restart: "no"
    depends_on: 
      - database
    
  authserver:
    container_name: AuthServer
    image: ghcr.io/mns-collect-verything/authserver:master
    restart: always
    ports:
      - '7600:7600'
    depends_on:
      database :
        condition: service_started
      migrator:
        condition: service_completed_successfully
