name: collecteverything-dev
services:
  database:
    container_name: Postgre
    image: postgres:16.2-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-volume:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres

  redis:
    container_name: Redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis-volume:/data

  rabbitmq:
    container_name: EventBus_RabbitMQ
    image: rabbitmq:3.13.1-alpine
    restart: always
    ports:
      - '5672:5672'
    volumes:
      - ./rabbitmq_volume/data:/var/lib/rabbitmq/
      - ./rabbitmq_volume/logs:/var/log/rabbitmq/
  
  migrator:
    container_name: Migrator
    image: dbmigrator:dev
    build:
      context: ../
      dockerfile: shared/CollectEverything.DbMigrator/Dockerfile
    restart: no
#    environment:
#      - ASPNETCORE_ENVIRONMENT=development
#      - DOTNET_ENVIRONMENT=development
    depends_on: 
      - database

  authserver:
    container_name: AuthServer
    image: authserver:dev
    build:
      context: ../
      dockerfile: apps/CollectEverything.AuthServer/Dockerfile
    restart: no
    ports:
      - '7600:8080'
      - '7601:8081'
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_ENVIRONMENT=development
      - ASPNETCORE_HTTPS_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./certificates/actual_certificates/:/https:ro
    depends_on:
      database :
        condition: service_started
      migrator:
        condition: service_completed_successfully

  gateway:
    container_name: Gateway
    image: gateway:dev
    build:
      context: ../
      dockerfile : gateway/CollectEverything.Gateway/Dockerfile
    restart: no
    ports:
      - '7500:8080'
      - '7501:8081'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
        - ./certificates/actual_certificates/:/https:ro
    depends_on:
      migrator:
        condition: service_completed_successfully

  administrationservice:
    container_name: Administration-service
    image: administration-service:dev
    build:
      context: ../
      dockerfile: services/administration/host/CollectEverything.Administration.HttpApi.Host/Dockerfile 
    restart: no
    ports:
      - '7001:8080'
      - '7101:8081'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./certificates/actual_certificates/:/https:ro
    depends_on:
      migrator:
        condition: service_completed_successfully

  identityservice:
    container_name: Identity-service
    image: identity-service:dev
    build:
      context: ../
      dockerfile: services/identity/host/CollectEverything.IdentityService.HttpApi.Host/Dockerfile
    restart: no
    ports:
      - '7002:8080'
      - '7102:8081'
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_ENVIRONMENT=development
      - ASPNETCORE_HTTPS_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./certificates/actual_certificates/:/https:ro
    depends_on:
      migrator:
        condition: service_completed_successfully

  saasservice:
    container_name: Saas-service
    image: saas-service:dev
    build:
      context: ../
      dockerfile: services/saas/host/CollectEverything.SaaS.HttpApi.Host/Dockerfile
    restart: no
    ports:
      - '7003:8080'
      - '7103:8081'
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_ENVIRONMENT=development
      - ASPNETCORE_HTTPS_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./certificates/actual_certificates/:/https:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
  
  productservice:
    container_name: Product-service
    image: product-service:dev
    build:
      context: ../
      dockerfile: services/product/host/CollectEverything.Product.HttpApi.Host/Dockerfile
    restart: no
    ports:
      - '7004:8080'
      - '7104:8081'
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_ENVIRONMENT=development
      - ASPNETCORE_HTTPS_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./certificates/actual_certificates/:/https:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
#  frontblazor:
#    container_name: FrontBlazor
#    image: frontblazor:dev
#    build:
#      context: ../
#      dockerfile: apps/CollectEverything.BlazorServer/Dockerfile
#    restart: always
#    ports:
#      - '5000:5000'
#      - '5001:5001'
#    environment:
##      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://pierremih.freeboxos.fr:5000;http://pierremih.freeboxos.fr:5001
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#    volumes:
#      - ~/.aspnet/https:/https:ro
#    depends_on:
#      migrator:
#        condition: service_completed_successfully
  frontblazor:
    container_name: FrontBlazor
    image: frontblazor:dev
    build:
      context: ../
      dockerfile: apps/CollectEverything.BlazorServer/Dockerfile
    restart: no
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://pierremih.freeboxos.fr:5000/
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./certificates/actual_certificates/:/https:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
