name: Collect&Verything CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build the Gateway Docker image
      run: docker build . --file gateway/CollectEverything.Gateway/Dockerfile --tag gateway:dev
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/gateway
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [ [ "${{ github.ref }}" == "refs/tags/"* ] ] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
    - name: Build the IdentityServer Docker image
      run: docker build . --file apps/CollectEverything.AuthServer/Dockerfile --tag authserver:dev
    - name: Build the Administration Docker image
      run: docker build . --file services/administration/host/CollectEverything.Administration.HttpApi.Host/Dockerfile --tag administration:dev
    - name: Build the IdentityService Docker image
      run: docker build . --file services/identity/host/CollectEverything.IdentityService.HttpApi.Host/Dockerfile --tag identityservice:dev
    - name: Build the SaaS Docker image
      run: docker build . --file services/saas/host/CollectEverything.SaaS.HttpApi.Host/Dockerfile --tag saas:dev
